name: monitoring-stack

services:
    grafana:
        image: grafana/grafana
        container_name: auth-api-grafana
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            #- GF_AUTH_ANONYMOUS_ENABLED=true
            #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - "3000:3000"
        volumes:
            - grafana-storage:/var/lib/grafana
        networks:
            - monitoring

    loki:
        image: grafana/loki:latest
        container_name: auth-api-loki
        ports:
            - "3100:3100"
        networks:
            - monitoring

    promtail:
        image: grafana/promtail:2.9.4
        container_name: auth-api-promtail
        volumes:
            - ./.docker/monitoring/promtail/config.yml:/etc/promtail/config.yml
            - ./.docker/app/storage/logs:/var/www/storage/logs
            - ./.docker/nginx/logs:/var/log/nginx
            - ./.docker/monitoring/promtail/positions.yml:/tmp/positions.yaml:rw
        networks:
            - monitoring
        command: -config.file=/etc/promtail/config.yml

    tempo:
        image: grafana/tempo:2.3.1
        container_name: auth-api-tempo
        ports:
            - "4318:4318"
            - "3200:3200"
        command: ["--config.file=/etc/tempo.yml"]
        volumes:
            - ./.docker/monitoring/tempo/config.yml:/etc/tempo.yml
            - ./.docker/monitoring/tempo/data:/tmp/tempo
        networks:
            - monitoring

networks:
    monitoring:
        name: auth_api_network
        external: true

volumes:
    grafana-storage:
