filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/laravel/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "elastic"

output.file:
  enabled: false